# Generated by Django 4.0.4 on 2022-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='姓名')),
                ('student_number', models.IntegerField(help_text='学号', unique=True, verbose_name='学号')),
                ('age', models.IntegerField(db_index=True, help_text='年龄', verbose_name='年龄')),
                ('cls', models.CharField(help_text='班级', max_length=4, verbose_name='班级')),
                ('score', models.FloatField(default=0.0, help_text='分数', verbose_name='分数')),
                ('remake', models.CharField(help_text='备注', max_length=200, verbose_name='备注')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
